# Generated by Django 5.0.2 on 2025-04-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_revision_created_at_alter_revision_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='revision',
            name='version',
        ),
    ]
