# Generated by Django 5.0.2 on 2025-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_revision_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
