# Generated by Django 5.0.2 on 2025-04-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_revision_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='created_by',
        ),
    ]
