# Generated by Django 5.0.2 on 2025-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_revision_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
