# Generated by Django 5.0.2 on 2025-04-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_revision_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='story',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.story', verbose_name='story'),
            preserve_default=False,
        ),
    ]
