# Generated by Django 5.0.2 on 2025-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_media_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='emotion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
