# Generated by Django 5.0.2 on 2025-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scene_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
