# Generated by Django 5.0.2 on 2025-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_media_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
