# Generated by Django 5.0.2 on 2025-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_scene_is_active_story_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='request_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='request id'),
        ),
    ]
