# Generated by Django 5.0.2 on 2025-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
