# Generated by Django 5.0.2 on 2025-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
