# Generated by Django 5.0.2 on 2025-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_revision_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
