# Generated by Django 5.0.2 on 2025-06-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='AWS SQS Message ID', max_length=100, unique=True)),
                ('job_type', models.CharField(choices=[('generate_media', 'Generate Media'), ('generate_pdf_preview', 'Generate PDF Preview'), ('generate_audio_preview', 'Generate Audio Preview'), ('generate_video_preview', 'Generate Video Preview'), ('generate_entire_audio', 'Generate Entire Audio')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_data', models.JSONField(help_text='Original request data sent to SQS')),
                ('response_data', models.JSONField(blank=True, help_text='Response data from the job', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed', null=True)),
                ('credit_cost', models.PositiveIntegerField(default=0, help_text='Number of credits required for this job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('credit_transaction', models.ForeignKey(blank=True, help_text='Associated credit transaction for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.credittransaction')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.scene')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_job_status_4b2344_idx'), models.Index(fields=['job_type'], name='core_job_job_typ_5d260f_idx'), models.Index(fields=['created_at'], name='core_job_created_8e7744_idx'), models.Index(fields=['user', 'status'], name='core_job_user_id_70041c_idx')],
            },
        ),
    ]
