# Generated by Django 5.0.2 on 2025-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='message_id',
            field=models.CharField(blank=True, help_text='AWS SQS Message ID', max_length=100, null=True, unique=True),
        ),
    ]
