# Generated by Django 5.0.2 on 2025-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_job_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(blank=True, default='en-US', help_text='Language of the story', max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='en-US', help_text='Language of the user', max_length=50, null=True, verbose_name='language'),
        ),
    ]
