# Generated by Django 5.0.2 on 2025-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_story_language_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is_private'),
        ),
    ]
