# Generated by Django 5.0.2 on 2025-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_story_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='story',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
    ]
